const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const UserVehicleRtoData = sequelize.define('UserVehicleRtoData', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    vehicle_number: { type: DataTypes.STRING(50) },
    engine_number: { type: DataTypes.STRING(100) },
    chasis_number: { type: DataTypes.STRING(100) },
    rc_regn_no: DataTypes.STRING(20),
    rc_regn_dt: DataTypes.DATEONLY,
    rc_regn_upto: DataTypes.DATEONLY,
    rc_purchase_dt: DataTypes.DATEONLY,
    rc_owner_sr: DataTypes.STRING(10),
    rc_owner_name: DataTypes.STRING(100),
    state_cd: DataTypes.STRING(10),
    rto_cd: DataTypes.STRING(10),
    api_response_message: DataTypes.STRING(255),
    rc_present_address: DataTypes.STRING(255),
    rc_permanent_address: DataTypes.STRING(255),
    rc_vch_catg: DataTypes.STRING(20),
    rc_vh_class_desc: DataTypes.STRING(50),
    rc_chasi_no: DataTypes.STRING(50),
    rc_eng_no: DataTypes.STRING(50),
    rc_maker_desc: DataTypes.STRING(100),
    rc_maker_model: DataTypes.STRING(100),
    rc_body_type_desc: DataTypes.STRING(50),
    rc_fuel_desc: DataTypes.STRING(20),
    rc_color: DataTypes.STRING(20),
    rc_norms_desc: DataTypes.STRING(50),
    rc_fit_upto: DataTypes.DATEONLY,
    rc_np_upto: DataTypes.DATEONLY,
    rc_np_issued_by: DataTypes.STRING(50),
    rc_tax_upto: DataTypes.DATEONLY,
    rc_financer: DataTypes.STRING(100),
    rc_insurance_comp: DataTypes.STRING(100),
    rc_insurance_policy_no: DataTypes.STRING(50),
    rc_insurance_upto: DataTypes.DATEONLY,
    rc_manu_month_yr: DataTypes.STRING(20),
    rc_unld_wt: DataTypes.STRING(20),
    rc_gvw: DataTypes.STRING(20),
    rc_no_cyl: DataTypes.STRING(10),
    rc_cubic_cap: DataTypes.STRING(20),
    rc_seat_cap: DataTypes.STRING(10),
    rc_sleeper_cap: DataTypes.STRING(10),
    rc_stand_cap: DataTypes.STRING(10),
    rc_wheelbase: DataTypes.STRING(20),
    rc_registered_at: DataTypes.STRING(100),
    rc_status_as_on: DataTypes.DATEONLY,
    rc_pucc_upto: DataTypes.DATEONLY,
    rc_pucc_no: DataTypes.STRING(50),
    rc_status: DataTypes.STRING(20),
    rc_ncrb_status: DataTypes.STRING(20),
    rc_blacklist_status: DataTypes.STRING(20),
    rc_permit_no: DataTypes.STRING(50),
    rc_permit_issue_dt: DataTypes.DATEONLY,
    rc_permit_valid_from: DataTypes.DATEONLY,
    rc_permit_valid_upto: DataTypes.DATEONLY,
    rc_permit_type: DataTypes.STRING(100),
    rc_permit_code: DataTypes.STRING(20),
    rc_noc_details: DataTypes.STRING(255),
    rc_vh_type: DataTypes.STRING(10),
    rc_vh_class: DataTypes.STRING(10),
    rc_noc_dt: DataTypes.STRING(20),
    rc_fuel_cd: DataTypes.STRING(10),
    rc_maker_cd: DataTypes.STRING(20),
    rc_model_cd: DataTypes.STRING(50),
    rc_norms_cd: DataTypes.STRING(10),
    rc_sale_amt: DataTypes.DECIMAL(15,2),
    rc_own_catg_desc: DataTypes.STRING(50),
    rc_vch_catg_desc: DataTypes.STRING(50),
    rc_owner_cd_desc: DataTypes.STRING(50),
    rc_vehicle_surrendered_to_dealer: DataTypes.STRING(5),
    rc_currentadd_districtcode: DataTypes.STRING(10),
    rc_non_use: DataTypes.STRING(10),
    rc_passenger_tax: DataTypes.STRING(20),
    rc_goods_tax: DataTypes.STRING(20),
    rc_no_of_axle: DataTypes.STRING(10),
    rc_qr_url: DataTypes.STRING(255),
    rc_auth_name: DataTypes.STRING(100),
    rc_auth_sign: DataTypes.STRING(100),
    rc_approval_date: DataTypes.STRING(20),
    rc_hp: DataTypes.STRING(20),
    rc_mandal_desc: DataTypes.STRING(50),
    rc_taluk_cd: DataTypes.STRING(20),
    rc_permit_catg: DataTypes.STRING(20),
    rc_tax_mode: DataTypes.STRING(10),
    rc_permit_issuing_authority: DataTypes.STRING(100),
    rc_width: DataTypes.STRING(20),
    rc_fitness_result: DataTypes.STRING(50),
    stautsMessage: DataTypes.STRING(20),
    rc_deemed_auc_valid_upto: DataTypes.STRING(20),
    rc_deemed_authorization_certificate_number: DataTypes.STRING(50),
    rc_deemed_dealer_code: DataTypes.STRING(20),
    rc_deemed_dealer_mail: DataTypes.STRING(100),
    rc_deemed_dealer_mobile: DataTypes.STRING(20),
    rc_deemed_dealer_name: DataTypes.STRING(100),
    rc_dealer_contact_no: DataTypes.STRING(20),
    rc_dealer_district: DataTypes.STRING(50),
    rc_dealer_pincode: DataTypes.STRING(20),
    rc_owner_history_offName: DataTypes.STRING(100),
    rc_owner_history_owner_name: DataTypes.STRING(100),
    rc_owner_history_owner_sr: DataTypes.STRING(10),
    rc_owner_history_stateCd: DataTypes.STRING(10),
    temp_permit_catg: DataTypes.STRING(20),
    temp_permit_code: DataTypes.STRING(20),
    temp_permit_issue_dt: DataTypes.STRING(20),
    temp_permit_no: DataTypes.STRING(50),
    temp_permit_type: DataTypes.STRING(50),
    temp_permit_valid_from: DataTypes.STRING(20),
    temp_permit_valid_upto: DataTypes.STRING(20),
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  }, {
    tableName: 'di_user_vehicle_rto_data',
    timestamps: false
  });
  return UserVehicleRtoData;
};
